import { NOTIFICATION_OR_TYPE } from '../enums/notification-or-type.enum';
import { OFFER_REQUEST_STATUS } from '../enums/offer-request-status.enum';

export const NOTIFICATION_OR_TYPE_MAPPING = {
  [OFFER_REQUEST_STATUS.ACCEPTED]: NOTIFICATION_OR_TYPE.OFFER_REQUEST_ACCEPTED,
  [OFFER_REQUEST_STATUS.REJECTED]: NOTIFICATION_OR_TYPE.OFFER_REQUEST_REJECTED,
};
